// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTB.BaChr.Mapy.Infrastructure.Database;

#nullable disable

namespace UTB.BaChr.Mapy.Infrastructure.Migrations
{
    [DbContext(typeof(MapyDbContext))]
    [Migration("20251215151912_Login_Register_2")]
    partial class Login_Register_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<double?>("MapX")
                        .HasColumnType("double");

                    b.Property<double?>("MapY")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Henryho strážní věž. Domov daleko od domova.",
                            MapX = 1175.0,
                            MapY = 1240.0,
                            Name = "Two Forks Tower"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thorofare Lookout. Věž, kde slouží Delilah.",
                            MapX = 1650.0,
                            MapY = 1600.0,
                            Name = "Delilah's Tower"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Klidné jezero ideální pro rybaření a přemýšlení.",
                            MapX = 1350.0,
                            MapY = 950.0,
                            Name = "Jonesy Lake"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Místo s nádherným výhledem na celé údolí.",
                            MapX = 900.0,
                            MapY = 1450.0,
                            Name = "Beartooth Point"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Oplocená výzkumná stanice. Vstup zakázán.",
                            MapX = 700.0,
                            MapY = 1100.0,
                            Name = "Wapiti Station"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Potok protékající jižní částí lesa.",
                            MapX = 1400.0,
                            MapY = 600.0,
                            Name = "Cottonwood Creek"
                        });
                });

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
