// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTB.BaChr.Mapy.Infrastructure.Database;

#nullable disable

namespace UTB.BaChr.Mapy.Infrastructure.Migrations
{
    [DbContext(typeof(MapyDbContext))]
    partial class MapyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<double?>("MapX")
                        .HasColumnType("double");

                    b.Property<double?>("MapY")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Henryho strážní věž. Domov daleko od domova.",
                            MapX = 1268.0,
                            MapY = 1395.0,
                            Name = "Two Forks Tower"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thorofare Lookout. Věž, kde slouží Delilah.",
                            MapX = 1132.0,
                            MapY = 225.0,
                            Name = "Delilah's Tower"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Klidné jezero ideální pro rybaření a přemýšlení.",
                            MapX = 275.0,
                            MapY = 1206.0,
                            Name = "Jonesy Lake"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Místo s nádherným výhledem na celé údolí.",
                            MapX = 1283.0,
                            MapY = 323.0,
                            Name = "Beartooth Point"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Oplocená výzkumná stanice. Vstup zakázán.",
                            MapX = 562.0,
                            MapY = 770.0,
                            Name = "Wapiti Station"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Potok protékající jižní částí lesa.",
                            MapX = 1013.0,
                            MapY = 1787.0,
                            Name = "Cottonwood Creek"
                        });
                });

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.cz",
                            Name = "Hlavní Administrátor",
                            PasswordHash = "admin",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "klient@klient.cz",
                            Name = "Testovací Klient",
                            PasswordHash = "klient",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.Comment", b =>
                {
                    b.HasOne("UTB.BaChr.Mapy.Domain.Entities.Location", "Location")
                        .WithMany("Comments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTB.BaChr.Mapy.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.Photo", b =>
                {
                    b.HasOne("UTB.BaChr.Mapy.Domain.Entities.Location", "Location")
                        .WithMany("Photos")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UTB.BaChr.Mapy.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTB.BaChr.Mapy.Domain.Entities.Location", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
